# Generated by Django 4.2 on 2024-07-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntry',
            new_name='Journal',
        ),
    ]
